spring.datasource:
  name: scheduler_ds
  # https://jdbc.postgresql.org/documentation/head/connect.html#connection-parameters
  url: jdbc:postgresql://localhost:5432/scheduler?connectTimeout=10&socketTimeout=40
  username: scheduler
  password: "schedulerPazZw0rd"
  driverClassName: org.postgresql.Driver

db-scheduler-data-mover:
  threads: 1
  table-name: scheduled_tasks_data_mover

db-scheduler-failing:
  threads: 1
  table-name: scheduled_tasks_failing